### PR TITLE
created pull request

### PR DESCRIPTION
**Pull request by swayam50**

### CODE REVIEW

**Comment by swayam50** [comment]
Finally created a pull request.

**Review by Vatsalparsaniya — CHANGES_REQUESTED** [review]
@swayam50 Great Work 👏

1) you need to add information in `markdown(md)` file, not in `txt` file
- all data should be in `Readme.md` file not in `Standadization_Normalization.txt `

you can refer this doc for markdown formatting [here](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

---
things you need to do:
1) remove both files 
2) add only `Readme.md` file and add all your information in `Readme.md` file only with proper formating

if you find any difficulty feel free to ask me

**Comment by swayam50** [comment]
Where should I put the standardization file and in which format?

**Comment by Vatsalparsaniya** [comment]
you need to remove `standardization.txt` file and data present in `standardization.txt` file paste into `Readme.md`

**Comment by swayam50** [comment]
Made the changes and saved it in a README.md file

**Review by Vatsalparsaniya — APPROVED** [review]

**Comment by Vatsalparsaniya** [comment]
Great Work @swayam50  👏

**Pull request merged**
