### PR TITLE
Added new folder "harmful object detection"

### PR DESCRIPTION
**Pull request by agasheaditya**
Added a new folder for harmful object detection using HAAR Cascade OpenCV. The cascades are trained on a custom-made knife dataset.

### CODE REVIEW

**Comment by Vatsalparsaniya** [comment]
Great work @agasheaditya,
as I have mentioned in the project Description
```
create Readme.md file in your folder add your knowledge there
You can add knowledge in Readme.md like:
    Why this concept
    How this algorithm works
    Advantages
    Disadvantages
    What Are the Basic Assumption
    In which problem statement you can your this concept or Algorithm
```
you should have to add Readme.md file into your folder and add your knowledge of `harmful object detection` in that file so, People can easily understand your contributions.
* Only thing you have to do is that add detailed `Readme.md` file into your folder

Thank you.

**Comment by agasheaditya** [comment]
Yes @Vatsalparsaniya I'll update the directory,

**Comment by agasheaditya** [comment]
@Vatsalparsaniya I have added the readme.md file to the folder but unable to merge and create a pull request. Please Check.
Thank You

**Review by Vatsalparsaniya — APPROVED** [review]

**Comment by Vatsalparsaniya** [comment]
Great work @agasheaditya

**Pull request merged**
